# .github/workflows/check-pr.yml

# Secrets and variables required:
# - secrets:
#   - ORG_CICD_TOKEN
#   - ORG_S3_ACCESS_KEY
#   - ORG_S3_SECRET_KEY
#   - ORG_S3_BUCKET_NAME
#   - ORG_S3_ENDPOINT_URL
#   - ORG_S3_REGION_NAME
#   - ORG_DOCKER_REGISTRY_URL
#   - ORG_DOCKER_REGISTRY_USERNAME
#   - ORG_DOCKER_REGISTRY_PASSWORD
#   
#   - ORG_ODOOHOST_EMAIL
#   - ORG_ODOOHOST_PASSWORD
#   - ORG_SEND_REPORT_COVERAGE_TO_ODOOHOST (optional, default: "0")
# - variables:
#   - ENABLE_ORG_CICD_CHECK_PR_TESTS
#   - ENABLE_REPO_CICD_CHECK_PR_TESTS
#   - REPO_CICD_CHECK_PR_TARGET_BRANCHES
#   - REPO_CICD_CHECK_PR_TESTS_BRANCHES_JSON_SETTINGS
#   - ORG_ODOOHOST_BASE_URL

name: Check PR Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-cli-command:
    runs-on: ubuntu-latest

    steps:

      - name: Action Deshabilitada por configuración
        if: ${{ vars.ENABLE_ORG_CICD_CHECK_PR_TESTS != 1 || vars.ENABLE_REPO_CICD_CHECK_PR_TESTS != 1 }}
        run: |
          echo "⚠️ Las configuraciones de activación no están habilitadas:"
          echo "ENABLE_ORG_CICD_CHECK_PR_TESTS=${{ vars.ENABLE_ORG_CICD_CHECK_PR_TESTS }}"
          echo "ENABLE_REPO_CICD_CHECK_PR_TESTS=${{ vars.ENABLE_REPO_CICD_CHECK_PR_TESTS }}"
          echo "REPO_CICD_CHECK_PR_TARGET_BRANCHES=${{ vars.REPO_CICD_CHECK_PR_TARGET_BRANCHES }}"
          echo "Saliendo sin ejecutar tests."
          exit 0

      - name: Validar configuración requerida
        id: check_required_settings
        if: ${{ vars.ENABLE_ORG_CICD_CHECK_PR_TESTS == '1' && vars.ENABLE_REPO_CICD_CHECK_PR_TESTS == '1' }}
        run: |
          echo "🔍 Validando rama destino: ${{ github.event.pull_request.base.ref }}"

          ALLOWED_BRANCHES="${{ vars.REPO_CICD_CHECK_PR_TARGET_BRANCHES }}"
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          HABILITADO=0
          IFS=',' read -ra ALLOWED <<< "$ALLOWED_BRANCHES"
          for branch in "${ALLOWED[@]}"; do
            if [[ "$branch" == "$BASE_REF" ]]; then
              HABILITADO=1
            fi
          done
          echo "allow_run_next_steps=$HABILITADO" >> $GITHUB_OUTPUT

          if [[ $HABILITADO -eq 0 ]]; then
            echo "⚠️ La rama '$BASE_REF' no está permitida para este workflow."
            echo "Saliendo sin ejecutar tests."
            exit 0
          else
            echo "✅ Rama permitida: $BASE_REF"
          fi

          # -----------------------------------

          echo "🔍 Validando configuración..."

          echo "🔧 Variables de configuración requeridas:"
          cat <<EOF
          Secrets and variables required:
            - secrets:
              - ORG_CICD_TOKEN
              - ORG_S3_ACCESS_KEY
              - ORG_S3_SECRET_KEY
              - ORG_S3_BUCKET_NAME
              - ORG_S3_ENDPOINT_URL
              - ORG_S3_REGION_NAME
              - ORG_DOCKER_REGISTRY_URL
              - ORG_DOCKER_REGISTRY_USERNAME
              - ORG_DOCKER_REGISTRY_PASSWORD
              - ORG_ODOOHOST_EMAIL
              - ORG_ODOOHOST_PASSWORD
            - variables:
              - ENABLE_ORG_CICD_CHECK_PR_TESTS
              - ENABLE_REPO_CICD_CHECK_PR_TESTS
              - REPO_CICD_CHECK_PR_TARGET_BRANCHES
              - REPO_CICD_CHECK_PR_TESTS_BRANCHES_JSON_SETTINGS
              - ORG_ODOOHOST_BASE_URL
          EOF

          # 
          [[ -z "${{ vars.REPO_CICD_CHECK_PR_TARGET_BRANCHES }}" ]] && echo "❌ Falta REPO_CICD_CHECK_PR_TARGET_BRANCHES" && exit 1
          [[ -z "${{ vars.REPO_CICD_CHECK_PR_TESTS_BRANCHES_JSON_SETTINGS }}" ]] && echo "❌ Falta REPO_CICD_CHECK_PR_TESTS_BRANCHES_JSON_SETTINGS" && exit 1
          [[ -z "${{ secrets.ORG_CICD_TOKEN }}" ]] && echo "❌ Falta ORG_CICD_TOKEN" && exit 1

          # S3
          [[ -z "${{ secrets.ORG_S3_ACCESS_KEY }}" ]] && echo "❌ Falta ORG_S3_ACCESS_KEY" && exit 1
          [[ -z "${{ secrets.ORG_S3_SECRET_KEY }}" ]] && echo "❌ Falta ORG_S3_SECRET_KEY" && exit 1
          [[ -z "${{ secrets.ORG_S3_BUCKET_NAME }}" ]] && echo "❌ Falta ORG_S3_BUCKET_NAME" && exit 1
          [[ -z "${{ secrets.ORG_S3_ENDPOINT_URL }}" ]] && echo "❌ Falta ORG_S3_ENDPOINT_URL" && exit 1
          [[ -z "${{ secrets.ORG_S3_REGION_NAME }}" ]] && echo "❌ Falta ORG_S3_REGION_NAME" && exit 1

          # Docker Registry
          [[ -z "${{ secrets.ORG_DOCKER_REGISTRY_URL }}" ]] && echo "❌ Falta ORG_DOCKER_REGISTRY_URL" && exit 1
          [[ -z "${{ secrets.ORG_DOCKER_REGISTRY_USERNAME }}" ]] && echo "❌ Falta ORG_DOCKER_REGISTRY_USERNAME" && exit 1
          [[ -z "${{ secrets.ORG_DOCKER_REGISTRY_PASSWORD }}" ]] && echo "❌ Falta ORG_DOCKER_REGISTRY_PASSWORD" && exit 1

          # OdooHost
          [[ -z "${{ vars.ORG_ODOOHOST_BASE_URL }}" ]] && echo "❌ Falta ORG_ODOOHOST_BASE_URL" && exit 1
          [[ -z "${{ secrets.ORG_ODOOHOST_EMAIL }}" ]] && echo "❌ Falta ORG_ODOOHOST_EMAIL" && exit 1
          [[ -z "${{ secrets.ORG_ODOOHOST_PASSWORD }}" ]] && echo "❌ Falta ORG_ODOOHOST_PASSWORD" && exit 1

          echo "✅ Todas las variables están presentes."

      - name: Ejecutar CLI desde mount-cicd-tool
        if: ${{ steps.check_required_settings.outputs.allow_run_next_steps == '1' &&  vars.ENABLE_ORG_CICD_CHECK_PR_TESTS == '1' && vars.ENABLE_REPO_CICD_CHECK_PR_TESTS == '1' }}
        uses: binaural-dev/.github-workflows-public/.github/actions/mount-cicd-tool@staging
        env:
          ORG_CICD_TOKEN: ${{ secrets.ORG_CICD_TOKEN }}
          S3_ACCESS_KEY: ${{ secrets.ORG_S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.ORG_S3_SECRET_KEY }}
          S3_BUCKET_NAME: ${{ secrets.ORG_S3_BUCKET_NAME }}
          S3_ENDPOINT_URL: ${{ secrets.ORG_S3_ENDPOINT_URL }}
          S3_REGION_NAME: ${{ secrets.ORG_S3_REGION_NAME }}
          DOCKER_REGISTRY_URL: ${{ secrets.ORG_DOCKER_REGISTRY_URL }}
          DOCKER_REGISTRY_USERNAME: ${{ secrets.ORG_DOCKER_REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.ORG_DOCKER_REGISTRY_PASSWORD }}
          ODOOHOST_BASE_URL: ${{ vars.ORG_ODOOHOST_BASE_URL }}
          ODOOHOST_EMAIL: ${{ secrets.ORG_ODOOHOST_EMAIL }}
          ODOOHOST_PASSWORD: ${{ secrets.ORG_ODOOHOST_PASSWORD }}
        with:
          TOOL_BRANCH: "rls_feature-ta_62762_add_coverage_report_to_action"
          CICD_TOKEN: ${{ secrets.ORG_CICD_TOKEN }}
          cli-command: |
            chcli devops code-review run-tests-from-pull-request-by-branch-settings \
              --pull_request_url https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} \
              --run_name '"Id: ${{ github.run_id }}"' \
              --branch_name ${{ github.event.pull_request.base.ref }} \
              --odoohost_base_url ${{ vars.ORG_ODOOHOST_BASE_URL }} \
              --odoohost_email ${{ secrets.ORG_ODOOHOST_EMAIL }} \
              --odoohost_password ${{ secrets.ORG_ODOOHOST_PASSWORD }} \
              --send_report_to_odoohost \
              --json-settings '${{ vars.REPO_CICD_CHECK_PR_TESTS_BRANCHES_JSON_SETTINGS }}'
