# Secrets and variables required:
# - variables:
#   - REPO_PRECOMMIT_MODE
#   - REPO_PRECOMMIT_CONFIG
#   - REPO_PRECOMMIT_REMOTE_CONFIGS
# - secrets:
#   - ORG_CICD_TOKEN
#   - ORG_S3_ACCESS_KEY
#   - ORG_S3_SECRET_KEY
#   - ORG_S3_BUCKET_NAME
#   - ORG_S3_ENDPOINT_URL
#   - ORG_S3_REGION_NAME

name: pre-commit

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: CHECK-REQUIRED_CONF
        run: |
          # GITHUB
          [[ -z "${{ secrets.ORG_CICD_TOKEN }}" ]] && echo "❌ Falta ORG_CICD_TOKEN" && exit 1

          # S3
          [[ -z "${{ secrets.ORG_S3_ACCESS_KEY }}" ]] && echo "❌ Falta ORG_S3_ACCESS_KEY" && exit 1
          [[ -z "${{ secrets.ORG_S3_SECRET_KEY }}" ]] && echo "❌ Falta ORG_S3_SECRET_KEY" && exit 1
          [[ -z "${{ secrets.ORG_S3_BUCKET_NAME }}" ]] && echo "❌ Falta ORG_S3_BUCKET_NAME" && exit 1
          [[ -z "${{ secrets.ORG_S3_ENDPOINT_URL }}" ]] && echo "❌ Falta ORG_S3_ENDPOINT_URL" && exit 1
          [[ -z "${{ secrets.ORG_S3_REGION_NAME }}" ]] && echo "❌ Falta ORG_S3_REGION_NAME" && exit 1

          # REPO CONFIG
          [[ -z "${{ vars.REPO_PRECOMMIT_MODE }}" ]] && echo "❌ Falta REPO_PRECOMMIT_MODE" && exit 1
          [[ -z "${{ vars.REPO_PRECOMMIT_REMOTE_CONFIGS }}" ]] && echo "❌ Falta REPO_PRECOMMIT_REMOTE_CONFIGS" && exit 1
          [[ -z "${{ vars.REPO_PRECOMMIT_REMOTE_CONFIGS_FOR_BRANCH }}" ]] && echo "❌ Falta REPO_PRECOMMIT_REMOTE_CONFIGS_FOR_BRANCH" && exit 1
          [[ -z "${{ vars.REPO_PRECOMMIT_FORCE_REMOTE_CONFIG_FOR_ODOO_VERSION_BRANCH }}" ]] && echo "❌ Falta REPO_PRECOMMIT_FORCE_REMOTE_CONFIG_FOR_ODOO_VERSION_BRANCH" && exit 1
          [[ -z "${{ vars.REPO_PRECOMMIT_INCLUDE_SUBMODULE }}" ]] && echo "❌ Falta REPO_PRECOMMIT_INCLUDE_SUBMODULE" && exit 1

          echo "✅ Todas las variables están presentes."
      - name: PRE-COMMIT CHECKS
        uses: binaural-dev/.github-workflows-public/.github/actions/install_bincli@release
        env:
          ORG_CICD_TOKEN: ${{ secrets.ORG_CICD_TOKEN }}
          S3_ACCESS_KEY: ${{ secrets.ORG_S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.ORG_S3_SECRET_KEY }}
          S3_BUCKET_NAME: ${{ secrets.ORG_S3_BUCKET_NAME }}
          S3_ENDPOINT_URL: ${{ secrets.ORG_S3_ENDPOINT_URL }}
          S3_REGION_NAME: ${{ secrets.ORG_S3_REGION_NAME }}
        with:
          BINCLI_BRANCH_OR_TAG: 'release'
          CICD_TOKEN: ${{ secrets.ORG_CICD_TOKEN }}
          cli-command: |
            chcli devops code-review pre-commit \
              --pull_request_url https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} \
              -m ${{ vars.REPO_PRECOMMIT_MODE }} \
              --remote-configs ${{ vars.REPO_PRECOMMIT_REMOTE_CONFIGS }} \
              --conditional-remote-config-for-branch ${{ vars.REPO_PRECOMMIT_REMOTE_CONFIGS_FOR_BRANCH }} \
              --apply-remote-config-for-branch ${{ github.event.pull_request.base.ref }} \
              --force-remote-config-for-odoo-version-branch ${{ vars.REPO_PRECOMMIT_FORCE_REMOTE_CONFIG_FOR_ODOO_VERSION_BRANCH }} \
              --include-submodule ${{ vars.REPO_PRECOMMIT_INCLUDE_SUBMODULE }}